# Generated by Django 2.2.9 on 2020-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
