# Generated by Django 2.2.9 on 2020-02-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0002_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
    ]
