# Generated by Django 2.2.9 on 2020-02-03 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myparking', '0003_remove_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
