# Generated by Django 2.2.9 on 2020-02-24 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='qrContent',
            new_name='hashId',
        ),
        migrations.AddField(
            model_name='reservation',
            name='codeReservation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etageAttribue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='placeAttribue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qrUrl',
            field=models.TextField(default='http://res.cloudinary.com/hhpni8wqv/image/upload/v1582544421/xgwesxnvfq9sc506racq.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.TextField(default='En cours'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 14, 6, 35, 916744)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 14, 6, 35, 916744)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 14, 6, 35, 916744)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 14, 6, 35, 916744)),
        ),
    ]
