# Generated by Django 2.2.9 on 2020-03-29 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationcluster',
            name='distanceMatrix',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=[], on_delete=django.db.models.deletion.DO_NOTHING, to='myparking_api.Distance'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 33, 14, 665471)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 33, 14, 665471)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 33, 14, 665471)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 33, 14, 665471)),
        ),
    ]
