# Generated by Django 2.2.9 on 2020-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0002_auto_20200215_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terme',
            name='contenu',
            field=models.TextField(),
        ),
    ]
