# Generated by Django 2.2.9 on 2020-04-18 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0002_auto_20200418_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='nbPlacesLibres',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 21, 16, 9, 270911)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 21, 16, 9, 270911)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 21, 16, 9, 270911)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 21, 16, 9, 270911)),
        ),
    ]
