# Generated by Django 2.2.9 on 2020-04-25 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0002_auto_20200329_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qrImage',
            field=models.ImageField(default='', upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 13, 17, 25, 962416)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 13, 17, 25, 962416)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 13, 17, 25, 962416)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 13, 17, 25, 962416)),
        ),
    ]
