# Generated by Django 2.2.9 on 2020-04-25 21:30

import datetime
from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0003_auto_20200425_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='myfiles/', collection='myfiles'), upload_to='test_images')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 22, 30, 17, 738624)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 22, 30, 17, 738624)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 22, 30, 17, 738624)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 22, 30, 17, 738624)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qrImage',
            field=models.ImageField(default='', storage=djongo.storage.GridFSStorage(base_url='myfiles/', collection='myfiles'), upload_to='qr_codes'),
        ),
    ]
