# Generated by Django 2.2.9 on 2020-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0003_auto_20200215_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaire',
            name='Jours',
        ),
        migrations.AddField(
            model_name='horaire',
            name='jour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
