# Generated by Django 2.2.9 on 2020-04-19 20:51

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0003_auto_20200418_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='centroid',
            field=djongo.models.fields.ListField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 50, 56, 723504)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 50, 56, 723504)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 50, 56, 723504)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 21, 50, 56, 723504)),
        ),
    ]
