# Generated by Django 2.2.9 on 2020-07-27 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0004_auto_20200620_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 34, 43, 969099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 43, 966100)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 43, 966100)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 43, 965100)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 43, 966100)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 43, 966100)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateDebut',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 34, 43, 968098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateFin',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 34, 43, 968098, tzinfo=utc)),
        ),
    ]
