# Generated by Django 2.2.9 on 2020-02-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0005_auto_20200217_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiment',
            name='type',
            field=models.TextField(),
        ),
    ]
