# Generated by Django 2.2.9 on 2020-04-22 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0006_auto_20200422_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='reservations',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, to='myparking_api.Reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 7, 9, 412223)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 7, 9, 412223)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 7, 9, 412223)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 21, 7, 9, 412223)),
        ),
    ]
