# Generated by Django 2.2.9 on 2020-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0006_auto_20200217_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='idAgent',
        ),
        migrations.RemoveField(
            model_name='automobiliste',
            name='idAutomobiliste',
        ),
        migrations.AddField(
            model_name='automobiliste',
            name='compte',
            field=models.TextField(default='app'),
        ),
        migrations.AddField(
            model_name='automobiliste',
            name='idCompte',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='iconUrl',
            field=models.TextField(default='https://image.flaticon.com/icons/svg/1835/1835948.svg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiment',
            name='iconUrl',
            field=models.URLField(default='https://image.flaticon.com/icons/png/512/66/66299.png'),
            preserve_default=False,
        ),
    ]
