# Generated by Django 2.2.9 on 2020-05-08 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0007_auto_20200422_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myparking_api.Parking'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 18, 57, 21, 910543)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 18, 57, 21, 910543)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 18, 57, 21, 910543)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 18, 57, 21, 910543)),
        ),
    ]
