# Generated by Django 2.2.9 on 2020-05-26 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0009_auto_20200509_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('dateDebut', models.DateTimeField(default=datetime.datetime(2020, 5, 26, 11, 39, 9, 100695, tzinfo=utc))),
                ('dateFin', models.DateTimeField(default=datetime.datetime(2020, 5, 26, 11, 39, 9, 100695, tzinfo=utc))),
                ('description', models.TextField()),
                ('attachedFiles', djongo.models.fields.ListField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 39, 9, 98697)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 39, 9, 98697)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 39, 9, 98697)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 39, 9, 98697)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 39, 9, 98697)),
        ),
    ]
