# Generated by Django 2.2.9 on 2020-05-26 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0010_auto_20200526_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='idAgent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myparking_api.Agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 30, 21, 414581)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 30, 21, 414581)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 30, 21, 414581)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 30, 21, 414581)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 30, 21, 414581)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateDebut',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 30, 21, 416579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateFin',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 30, 21, 416579, tzinfo=utc)),
        ),
    ]
