# Generated by Django 2.2.9 on 2020-05-26 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0011_auto_20200526_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='idAgent',
            new_name='agent',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 34, 26, 654031)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 34, 26, 654031)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 34, 26, 654031)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 34, 26, 654031)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 13, 34, 26, 654031)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateDebut',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 34, 26, 655030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='dateFin',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 12, 34, 26, 655030, tzinfo=utc)),
        ),
    ]
