# Generated by Django 2.2.9 on 2020-03-19 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myparking_api', '0012_auto_20200318_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobiliste',
            name='lattitude',
            field=models.FloatField(default=36.7449434),
        ),
        migrations.AddField(
            model_name='automobiliste',
            name='longitude',
            field=models.FloatField(default=3.1913014),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreeEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 11, 30, 180458)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateEntreePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 11, 30, 180458)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortieEffective',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 11, 30, 180458)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateSortiePrevue',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 21, 11, 30, 180458)),
        ),
    ]
